import 'package:flutter/cupertino.dart';

class SerchProvider extends ChangeNotifier {
  List serchPhotoList = [
    'assets/serch/img.png',
    'assets/serch/img_1.png',
    'assets/serch/img_2.png',
    'assets/serch/img_3.png',
    'assets/serch/img_4.png',
    'assets/serch/img_5.png',
    'assets/serch/img_6.png',
    'assets/logo/img_3.png',
    'assets/image/img_1.png',
    'assets/image/img.png',
    'assets/logo/img_1.png',
    'assets/logo/img_2.png',
    'assets/logo/img_3.png',
    'assets/serch/img.png',
    'assets/serch/img_1.png',
    'assets/serch/img_2.png',
    'assets/serch/img_3.png',
    'assets/serch/img_4.png',
    'assets/serch/img_5.png',
    'assets/serch/img_6.png',
    'assets/logo/img_3.png',
    'assets/image/img_1.png',
    'assets/image/img.png',
    'assets/logo/img_1.png',
    'assets/logo/img_2.png',
    'assets/logo/img_3.png',
    'assets/serch/img.png',
    'assets/serch/img_1.png',
    'assets/serch/img_2.png',
    'assets/serch/img_3.png',
    'assets/serch/img_4.png',
    'assets/serch/img_5.png',
    'assets/serch/img_6.png',
    'assets/logo/img_3.png',
    'assets/image/img_1.png',
    'assets/image/img.png',
    'assets/logo/img_1.png',
    'assets/logo/img_2.png',
    'assets/logo/img_3.png',
  ];
}
